import Header from "@/components/Header";
import Head from "next/head";
import type { PlayersType } from "@/types/playerType";
import { useEffect, useState } from "react";
import PlayersTable from "@/components/PlayersTable";

export default function Home() {
	const [players, setPlayers] = useState<PlayersType>();

	useEffect(() => {
		const options = { method: "GET" };

		fetch("http://localhost:3000/api/players", options)
			.then((response) => response.json())
			.then((response) => setPlayers(response))
			.catch((err) => console.error(err));
	}, []);

	return (
		<>
			<Head>
				<title>Fifa Mobile Players Database</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="mx-auto px-16 text-secondary-grey">
				<Header />
				<div className="mt-6">{players && <PlayersTable players={players} />}</div>
			</main>
		</>
	);
}
